<robot name="my_camera" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="camera_length_val" value="0.01" />
    <xacro:property name="camera_width_val" value="0.025" />
    <xacro:property name="camera_height_val" value="0.025" />
    <xacro:property name="camera_x_pos" value="0.08" />
    <xacro:property name="camera_y_pos" value="0.0" />
    <xacro:property name="camera_z_pos" value="${base_link_length / 2 + camera_height_val / 2}" />
    <xacro:property name="camera_m_val" value="0.01" />

    <link name="camera_link"> <!-- Renamed link to be more specific -->
        <visual>
            <geometry>
                <box size="${camera_length_val} ${camera_width_val} ${camera_height_val}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" /> <!-- Assuming 'black' is defined in car_base.xacro or main xacro -->
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length_val} ${camera_width_val} ${camera_height_val}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:Box_inertial_matrix m="${camera_m_val}" l="${camera_length_val}" w="${camera_width_val}" h="${camera_height_val}" />
    </link>

    <gazebo reference="camera_link">
        <material>Gazebo/Blue</material>
        <sensor type="camera" name="gazebo_camera_sensor">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>800</width>
                    <height>800</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>0.0</updateRate>
                <cameraName>mybot/camera1</cameraName>
                <imageTopicName>image_raw</imageTopicName>
                <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                <frameName>camera_link_optical</frameName> <!-- Important: Optical frame -->
                <hackBaseline>0.07</hackBaseline>
                <distortionK1>0.0</distortionK1>
                <distortionK2>0.0</distortionK2>
                <distortionK3>0.0</distortionK3>
                <distortionT1>0.0</distortionT1>
                <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo>

    <!-- Optical frame for camera, following ROS conventions -->
    <link name="camera_link_optical"/>
    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
    </joint>

    <joint name="camera_to_base_link" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${camera_x_pos} ${camera_y_pos} ${camera_z_pos}" />
    </joint>

</robot>