<robot name="my_laser" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="support_length_val" value="0.15" />
    <xacro:property name="support_radius_val" value="0.01" />
    <xacro:property name="support_x_pos" value="0.0" />
    <xacro:property name="support_y_pos" value="0.0" />
    <xacro:property name="support_z_pos" value="${base_link_length / 2 + support_length_val / 2}" />
    <xacro:property name="support_m_val" value="0.02" />

    <link name="support_link"> <!-- Renamed -->
        <visual>
            <geometry>
                <cylinder radius="${support_radius_val}" length="${support_length_val}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="red_vis"> <!-- Rviz specific color -->
                <color rgba="0.8 0.2 0.0 0.8" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${support_radius_val}" length="${support_length_val}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${support_m_val}" r="${support_radius_val}" h="${support_length_val}" />
    </link>

    <gazebo reference="support_link">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="support_to_base_link" type="fixed">
        <parent link="base_link" />
        <child link="support_link" />
        <origin xyz="${support_x_pos} ${support_y_pos} ${support_z_pos}" />
    </joint>

    <xacro:property name="laser_length_val" value="0.05" />
    <xacro:property name="laser_radius_val" value="0.03" />
    <xacro:property name="laser_x_pos" value="0.0" />
    <xacro:property name="laser_y_pos" value="0.0" />
    <xacro:property name="laser_z_pos" value="${support_length_val / 2 + laser_length_val / 2}" />
    <xacro:property name="laser_m_val" value="0.1" />

    <link name="laser_link"> <!-- Renamed -->
        <visual>
            <geometry>
                <cylinder radius="${laser_radius_val}" length="${laser_length_val}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" /> <!-- Assuming 'black' is defined -->
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius_val}" length="${laser_length_val}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m_val}" r="${laser_radius_val}" h="${laser_length_val}" />
    </link>

    <gazebo reference="laser_link">
        <material>Gazebo/Black</material>
        <!-- Add Gazebo Ray (Lidar) plugin -->
        <sensor type="ray" name="gazebo_lidar_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize> <!-- Set to true to see rays in Gazebo -->
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-${PI}</min_angle>
                        <max_angle>${PI}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser_link</frameName>
            </plugin>
        </sensor>
    </gazebo>

    <joint name="laser_to_support" type="fixed">
        <parent link="support_link" />
        <child link="laser_link" />
        <origin xyz="${laser_x_pos} ${laser_y_pos} ${laser_z_pos}" />
    </joint>
    
</robot>